security:
    # Hashage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Provider : cherche l'utilisateur par email
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Formulaire de login
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                # ← Après login réussi, on passe par dashboardRedirect()
                default_target_path: app_dashboard_redirect
                always_use_default_target_path: true

            # Déconnexion
             # Configuration logout
            logout:
                path: app_logout
                target: app_home  # Redirige vers la page d'accueil après déconnexion

            # Se souvenir de moi
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800  # 7 jours
                path: /

    # Contrôle d'accès par URL
    access_control:
        # Pages publiques
        - { path: ^/login,    roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/$,        roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }

        # Backend admin uniquement
        - { path: ^/admin,    roles: ROLE_ADMIN }
        - { path: ^/user,    roles: ROLE_ADMIN }



        # Front propriétaire
        - { path: ^/proprietaire, roles: ROLE_PROPRIETAIRE }
        - { path: ^/pet, roles: ROLE_PROPRIETAIRE }
        - { path: ^/announcement, roles: ROLE_PROPRIETAIRE }
        - { path: ^/announcement/.*/postuler, roles: ROLE_GARDIEN }



        # Front gardien
        - { path: ^/gardien,  roles: ROLE_GARDIEN }

    # Hiérarchie des rôles
    role_hierarchy:
        ROLE_ADMIN:        [ROLE_USER]
        ROLE_PROPRIETAIRE: [ROLE_USER]
        ROLE_GARDIEN:      [ROLE_USER]